Feat/rails init (#1)
rails init

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,51 +1,33 @@
-#!/bin/sh
+#!/usr/bin/env ruby
+require "fileutils"
 
-# Set up Rails app. Run this script immediately after cloning the codebase.
-# https://github.com/thoughtbot/guides/tree/master/protocol
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-# Exit if any subcommand fails
-set -e
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Set up Ruby dependencies via Bundler
-gem install bundler --conservative
-bundle check || bundle install
+FileUtils.chdir APP_ROOT do
+  # This script is a way to set up or update your development environment automatically.
+  # This script is idempotent, so that you can run it at any time and get an expectable outcome.
+  # Add necessary setup steps to this file.
 
-# Install JavaScript dependencies
-bin/yarn
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-# Set up database and add any development seed data
-bin/rails dev:prime
+  # puts "\n== Copying sample files =="
+  # unless File.exist?('config/database.yml')
+  #   FileUtils.cp 'config/database.yml.sample', 'config/database.yml'
+  # end
 
-if [ ! -d .git/safe ] && echo $PATH | grep .git/safe > /dev/null; then
-  echo "-----------------------------------------------------------------------"
-  echo
-  echo "-> When you trust this repo, remember to run: mkdir -p .git/safe"
-  echo
-fi
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:prepare'
 
-# Only if this isn't CI
-if [ -z "$CI" ]; then
-  cp -i .sample.env .env
-fi
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
 
-if heroku apps:info --app pbstm-app-api-staging > /dev/null 2>&1; then
-  git remote add staging git@heroku.com:pbstm-app-api-staging.git || true
-  printf 'You are a collaborator on the "pbstm-app-api-staging" Heroku app
-'
-else
-  printf 'Ask for access to the "pbstm-app-api-staging" Heroku app
-'
-fi
-
-
-if heroku apps:info --app pbstm-app-api-production > /dev/null 2>&1; then
-  git remote add production git@heroku.com:pbstm-app-api-production.git || true
-  printf 'You are a collaborator on the "pbstm-app-api-production" Heroku app
-'
-else
-  printf 'Ask for access to the "pbstm-app-api-production" Heroku app
-'
-fi
-
-
-git config heroku.remote staging
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
